In [1]:
import pandas as pd 
import numpy as np

In [6]:
df=pd.read_csv("DataCoSupplyChainDataset.csv",
              encoding="latin1")

In [8]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [12]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [17]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

1.First We Will Make and Copy And Delete unwanted Columns

In [18]:
data_clean=df.copy()

In [19]:
drop_cols=[
    'Customer Password',
    'Product Description',
    'Product Image',
    'Order Zipcode'
]

In [21]:

data_clean.drop(columns=drop_cols, inplace=True)

In [22]:
data_clean.shape

(180519, 49)

2.Then We Will Change Date Types

In [26]:
data_clean['order date (DateOrders)'] = pd.to_datetime(
    data_clean['order date (DateOrders)']
)

In [27]:
data_clean['shipping date (DateOrders)'] = pd.to_datetime(
    data_clean['shipping date (DateOrders)']
)

In [29]:
data_clean.dtypes.tail()

Product Name                          object
Product Price                        float64
Product Status                         int64
shipping date (DateOrders)    datetime64[ns]
Shipping Mode                         object
dtype: object

3.Now We Will Create Business Columns

In [32]:
data_clean['Delivery_Delay']=(
    data_clean['Days for shipping (real)']
    - data_clean['Days for shipment (scheduled)']
)

In [38]:
data_clean['Order_Year'] = (
    data_clean['order date (DateOrders)'].dt.year
)

In [34]:
data_clean['Order_Month'] = (
    data_clean['order date (DateOrders)'].dt.month_name()
)

In [35]:
data_clean['Order_Quarter'] = (
    data_clean['order date (DateOrders)'].dt.quarter
)

In [39]:
data_clean[
    ['Delivery_Delay',
     'Order_Year',
     'Order_Month',
     'Order_Quarter']
].head()

   Delivery_Delay  Order_Year Order_Month  Order_Quarter
0              -1        2018     January              1
1               1        2018     January              1
2               0        2018     January              1
3              -1        2018     January              1
4              -2        2018     January              1

In [41]:
data_clean.shape

(180519, 54)

In [44]:
data_clean.duplicated().sum()

np.int64(0)

4.Now Lets Start With EDA

Phase 1

(1).Revenue Overview

In [45]:
"Total_Revenue:",round(data_clean['Sales'].sum(),2)

('Total_Revenue:', np.float64(36784735.01))

In [46]:
print("Average Revenue:", round(data_clean['Sales'].mean(),2))

Average Revenue: 203.77

In [47]:
print("Maximum Sale:", round(data_clean['Sales'].max(),2))

Maximum Sale: 1999.99

In [48]:
print("Minimum Sale:", round(data_clean['Sales'].min(),2))

Minimum Sale: 9.99

(2).Top 10 Categories

In [49]:
category_sales = (
    data_clean.groupby('Category Name')['Sales']
    .sum()
    .sort_values(ascending=False)
)

In [50]:
category_sales.head(10)

Category Name
Fishing                 6.929654e+06
Cleats                  4.431943e+06
Camping & Hiking        4.118426e+06
Cardio Equipment        3.694843e+06
Women's Apparel         3.147800e+06
Water Sports            3.113845e+06
Men's Footwear          2.891758e+06
Indoor/Outdoor Games    2.888994e+06
Shop By Sport           1.309522e+06
Computers               6.630000e+05
Name: Sales, dtype: float64

(3).Delivery Performance

In [51]:
data_clean['Delivery Status'].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

(4).Shipping Mode Analysis

In [52]:
data_clean['Shipping Mode'].value_counts()

Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

(5).Customer Segment Analysis

In [53]:
data_clean.groupby(
    'Customer Segment'
)['Sales'].sum().sort_values(
    ascending=False
)

Customer Segment
Consumer       1.909579e+07
Corporate      1.116841e+07
Home Office    6.520538e+06
Name: Sales, dtype: float64

(6).Market Analysis

In [54]:
data_clean.groupby(
    'Market'
)['Sales'].sum().sort_values(
    ascending=False
)

Market
Europe          1.087240e+07
LATAM           1.027761e+07
Pacific Asia    8.273744e+06
USCA            5.066529e+06
Africa          2.294453e+06
Name: Sales, dtype: float64

(7).Top 10 Products

In [55]:
data_clean.groupby(
    'Product Name'
)['Sales'].sum().sort_values(
    ascending=False
).head(10)

Product Name
Field & Stream Sportsman 16 Gun Fire Safe        6.929654e+06
Perfect Fitness Perfect Rip Deck                 4.421143e+06
Diamondback Women's Serene Classic Comfort Bi    4.118426e+06
Nike Men's Free 5.0+ Running Shoe                3.667633e+06
Nike Men's Dri-FIT Victory Golf Polo             3.147800e+06
Pelican Sunstream 100 Kayak                      3.099845e+06
Nike Men's CJ Elite 2 TD Football Cleat          2.891758e+06
O'Brien Men's Neoprene Life Vest                 2.888994e+06
Under Armour Girls' Toddler Spine Surge Runni    1.269083e+06
Dell Laptop                                      6.630000e+05
Name: Sales, dtype: float64

5.Now We Will Create Dimension Tables and Fact Table For Power Bi Analysis

(1).Product Dimension

In [56]:
dim_product = data_clean[
[
'Product Card Id',
'Product Name',
'Category Name',
'Department Name',
'Product Price'
]
].drop_duplicates()

In [58]:
dim_product.shape

(118, 5)

(2).Customer Dimension

In [59]:
dim_customer = data_clean[
[
'Customer Id',
'Customer Segment',
'Customer City',
'Customer State',
'Customer Country'
]
].drop_duplicates()

In [60]:
dim_customer.shape

(20652, 5)

(3).Date Dimension

In [61]:
dim_date = data_clean[
[
'order date (DateOrders)',
'Order_Year',
'Order_Month',
'Order_Quarter'
]
].drop_duplicates()

In [62]:
dim_date.shape

(65752, 4)

(4).Fact Orders

In [63]:
fact_orders = data_clean[
[
'Order Id',
'Customer Id',
'Product Card Id',
'Sales',
'Benefit per order',
'Order Item Quantity',
'Shipping Mode',
'Delivery_Delay',
'Late_delivery_risk',
'order date (DateOrders)'
]
]

In [64]:
fact_orders.shape

(180519, 10)

Exporting Tables

In [65]:
# Export Product Dimension
dim_product.to_csv(
    'Dim_Product.csv',
    index=False,
    encoding='utf-8'
)

# Export Customer Dimension
dim_customer.to_csv(
    'Dim_Customer.csv',
    index=False,
    encoding='utf-8'
)

# Export Date Dimension
dim_date.to_csv(
    'Dim_Date.csv',
    index=False,
    encoding='utf-8'
)

# Export Fact Table
fact_orders.to_csv(
    'Fact_Orders.csv',
    index=False,
    encoding='utf-8'
)